[package]
authors = ["Zeke Sonxx <zeke@zekesonxx.com>"]
name = "steamlink-sdk-rs-maybe"
version = "0.1.0"

[dependencies]
sdl2 = "0.30.0"

[profile]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
